strains:
  - name: default
    content: https://github.com/trieloff/helix-demo.git#master
    static: https://github.com/hakimel/reveal.js.git#master
    code: ssh://git@github.com/trieloff/helix-slides.git#master
    package: trieloff/78fd20b0d855d1e3945f658f45963edfb3631e0e
